FROM alpine:3.12.0
RUN wget https://github.com/zeebe-io/zeebe-modeler/releases/download/v0.9.1/zeebe-modeler-0.9.1-linux-x64.tar.gz
RUN wget https://github.com/zeebe-io/zeebe-modeler/releases/download/v0.9.1/zeebe-modeler-0.9.1-win-x64.zip
