FROM alpine:3.12.0 
RUN wget https://dl.k8s.io/v1.19.2/kubernetes-server-linux-amd64.tar.gz
RUN wget https://dl.k8s.io/v1.19.2/kubernetes-node-linux-amd64.tar.gz
RUN wget https://get.helm.sh/helm-v3.3.3-linux-amd64.tar.gz